export type PokemonNameColor =
    | 'bug'
    | 'dark'
    | 'dragon'
    | 'eletric'
    | 'fairy'
    | 'fighting'
    | 'fire'
    | 'flying'
    | 'ghost'
    | 'grass'
    | 'ground'
    | 'ice'
    | 'normal'
    | 'poison'
    | 'psychic'
    | 'rock'
    | 'steel'
    | 'water'
    | 'red'
           
export type PokemonTypeColors = 
    |'bug'
    |'dark'
    |'dragon'
    |'eletric'
    |'fairy'
    |'fighting'
    |'fire'
    |'flying'
    |'ghost'
    |'grass'
    |'ground'
    |'ice'
    |'normal'
    |'poison'
    |'psychic'
    |'rock'
    |'steel'
    |'water'

     